  version: "3.9"

  services:
    robot:
      build: TestEntropy
      container_name: robot_test
      volumes:
        - ./reports:/opt/robotframework/reports  # maps reports folder
      environment:
        BROWSER: chrome  # default browser: chrome, can change to firefox or edge
      ports:
        - "5900:5900"    # optional: connect via VNC to see browser
      command: >
        sh -c "Xvfb :99 -screen 0 1920x1080x24 &
               robot --variable BROWSER:${BROWSER} --outputdir reports tests/"